[bumpver]
current_version = "0.3.0a1"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "Bump version: {old_version} → {new_version}"
tag_message = "v{new_version}"
tag_name = "v{new_version}"
files = [
    "setup.py",
    "CHANGELOG.md"
] 