name: Publish Pre-release to TestPyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: python -m pip install --upgrade pip build twine

      - name: Build package
        run: python -m build

      - name: Publish to TestPyPI (pre-releases only)
        if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, 'a')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: twine upload --repository testpypi dist/* 